### ISSUE TITLE
Development to-do list

### ISSUE THREAD

**Issue by pedrosancao** [pedrosancao/asciimath-tinymce4#1]
- [x] insert formula through button/menu - b33ed83
- [x] insert formula with the selected text - f23e6d6
- [x] preview in popup - c02f30b
- [x] integration with preview plugin - cd81561
- [x] link syntax - 0286fbd
- [x] manage "Enter" key while editing formula, prevent duplication of `span` controls - depend on keep_styles setting
- [x] support alignment options - discarted, for now
- [x] highlight editing area - ea0055f
- [x] create alternative to edit through button - b33ed83
- [x] actions before submit or get text - 1c4c391
- [ ] cut/copy formula then paste break the `span`
- [ ] verification to prevent inserting a formula within a formula (from paste)

**Comment by swaminator** [comment]
Hey, Thanks for this plugin.

How do I exit the asciimath after I enter a formula? Even when I hit 'Enter', it keeps propagating the p>span for everything I type additionally.

**Comment by pedrosancao** [comment]
thanks for reporting, I will add this as an issue
